#ifndef GRAPHSERIALIZATION_GLOBAL_H
#define GRAPHSERIALIZATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHSERIALIZATION_LIBRARY)
#  define GRAPHSERIALIZATION_EXPORT Q_DECL_EXPORT
#else
#  define GRAPHSERIALIZATION_EXPORT Q_DECL_IMPORT
#endif


#endif // GRAPHSERIALIZATION_GLOBAL_H
